from distutils.core import setup

setup(name='OPCReader',
      version='0.2',
      description='Reads CSV files generated by OPC-N2',
      author='Matthew Lodge',
      author_email='matthewlodge01@gmail.com',
      url='',
      packages=['OPCReader'],
      setup_requires=['numpy>=1.13.1', 'pandas>=0.20.3','matplotlib>=2.0']
     )